apiVersion: v1
kind: Service
metadata:
  labels:
    name: "{{ .Chart.Name }}-service"
  name: "{{ .Chart.Name }}-service"
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    app: "{{ .Chart.Name }}-deployment"
