apiVersion: v1
kind: Service
metadata:
  labels:
    name: "{{ .Chart.Name }}-hockey-service"
  name: "{{ .Chart.Name }}-hockey-service"
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: "{{ .Chart.Name }}-hockey-service"
